version: "3"
services:
    web:
        image: dshoreman/sample:latest
        deploy:
            replicas: 3
            reources:
                limits:
                    cpus: "0.1"
                    memory: 50M
                restart_policy:
                    condition: on-failure
            ports:
                - "80:80"
            networks:
                - webnet
networks:
    webnet:
